on: [push]
jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: "run the action test"
        id: hello
        uses: ./
        with:
          myInput: "Chad"
      - name: "run the output"
        run: |
          echo ${{ steps.hello.outputs.memory }}
          echo "Total memory successfully outputed"
